// Language Level Converter line number map: dj*->java. Entries: 20
//     1->5         2->6         3->7         4->8         5->9         6->10        7->11        8->12   
//     9->13       10->14       11->15       12->16       13->17       14->18       15->19       16->20   
//    17->21       18->22       19->23       20->24   
/**
 * Auto Generated Java Language Level Class.
 */
class TestPrimitives {
  
  /* ADD YOUR CODE HERE */
  public static void main(final String[] args) {
    final boolean isRaining=true;
    final double x=21.0;
    final String name = "Amy";
    final int i=21;
    System.out.println(isRaining);
    System.out.println(!isRaining);
    System.out.println(x/2 /*<=Widening*/);
    System.out.println(i/2);

  }
  
  

  /** This method is automatically generated by the Language Level Converter. */
  public TestPrimitives() {
    super();
  }

  /** This method is automatically generated by the Language Level Converter. */
  public java.lang.String toString() {
    return getClass().getName() + "(" + 
        ")";
  }

  /** This method is automatically generated by the Language Level Converter. */
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    else if ((o == null) || (! o.getClass().equals(getClass()))) {
      return false;
    }
    else {
      TestPrimitives cast = ((TestPrimitives) o);
      return true;
    }
  }

  /** This method is automatically generated by the Language Level Converter. */
  public int hashCode() {
    return getClass().hashCode();
  }
}
